version: '3'
# https://medium.com/@ilyas_24382/deploy-a-web-app-using-flask-and-docker-containers-96218e80e5fa

services:
  app:
    build: ./app
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://pstgr_user:pstgr_pass@dbcont:5432/pstgr_db
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    networks:
      - network

  db:
    build: ./db
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=bterral
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=to_do
    networks:
      - network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  network:

volumes:
  postgres_data: